name: Publish to noctalia-plugins

on:
  release:
    types: [published]

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Clone noctalia-plugins fork
        run: |
          git clone https://x-access-token:${{ secrets.NOCTALIA_PLUGINS_TOKEN }}@github.com/wizard-28/noctalia-plugins.git

      - name: Sync fork with upstream
        run: |
          cd noctalia-plugins

          git remote add upstream https://github.com/noctalia-dev/noctalia-plugins.git

          git fetch upstream

          # Safe as it's my fork
          git reset --hard upstream/main
          git push --force origin main

      - name: Copy files
        run: |
          set -e
          TARGET="noctalia-plugins/noctalia-vantage"

          rm -rf "${TARGET}"
          mkdir -p "${TARGET}"

          rsync -av --exclude='.git' \
              --exclude='.github' \
              --exclude="noctalia-plugins" \
              --exclude=".gitignore" \
              --exclude=".qmlls.ini" \
              ./ "$TARGET/"

      - name: Commit & Push
        run: |
          cd noctalia-plugins

          git config user.name "wizard-28"
          git config user.email "49679481+wizard-28@users.noreply.github.com"

          git add .
          git commit -m "noctalia-vantage: Update to ${{ github.event.release.tag_name }}"

          git push origin main
